version: '3'

networks:
  base-app-dev:

services:
  db:
    image: mariadb:10.5.4-focal
    container_name: base-app-dev-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - base-app-dev