version: '3'

networks:
  base-app:

services:
  db:
    image: mariadb:10.5.4-focal
    container_name: base-app-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - base-app
  server:
    build: base-app-server
    container_name: base-app-server
    restart: unless-stopped
    environment:
      spring.datasource.password: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - base-app
  ui:
    build: base-app-ui
    container_name: base-app-ui
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - base-app