version: '3'

networks:
  base-app:

services:
  db:
    image: mariadb:10.5.4-focal
    container_name: base-app-db
    restart: unless-stopped
    command: --max_allowed_packet=1024000000
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - base-app